### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by polyzen** [GothenburgBitFactory/tasklib#120]
It would be nice to get the [switch to zoneinfo](https://github.com/GothenburgBitFactory/tasklib/commit/0307266a6f1c53110f819064f8b79d00eb73c2d4) change out, so there is one less blocker for distributions to update to tzlocal 4.x.

**Comment by polyzen** [comment]
VIT has also been awaiting a release:
https://github.com/vit-project/vit/issues/300#issuecomment-975505850

**Comment by tbabej** [comment]
Tasklib 2.5.1 [has been released](https://pypi.org/project/tasklib/2.5.1/).
